### ISSUE TITLE
Wrapper script defective

### ISSUE THREAD

**Issue by ghost** [NBZion/SteamModDownloader#2]
I just checked again today and the wrapper script breaks because SWD is downloaded into a created directory instead of the current one. So, the script must download the repo, move all the files to the current directory, and delete the folder.
If not fixed, dependencies are not installed, and SWD will not be launched through the script.
(during my original testing I did not clone the repo as it would not have the patched files, but only launched the tool.)

**Comment by NBZion** [comment]
Ill fix soon when i have time

**Comment by ghost** [comment]
Already made a PR to fix this.
