### ISSUE TITLE
Reinstall deletes everything in source folder

### ISSUE THREAD

**Issue by Satyr-OS** [NBZion/SteamModDownloader#4]
i downloaded it and tried to reinstall it.
it deleted everything in the downloads folder.
could use a warning or protection there.

**Comment by NBZion** [comment]
Hello thank you for reporting! I request you to only use one issue to refrain from me going back and forth from each issue! Thank you in advance!

**Comment by NBZion** [comment]
Closed as noted and will update when I have the time!
