### ISSUE TITLE
./smd: line 97: ./.clientEnv/bin/python3: No such file or directory

### ISSUE THREAD

**Issue by Satyr-OS** [NBZion/SteamModDownloader#5]
i get this error when launching.
if there are prerequisites to run in it could be stated in the installation instructions.

**Comment by NBZion** [comment]
Thank you for using! Can you please send some more info on it? Maybe a screenshot of the terminal?

**Comment by Satyr-OS** [comment]
it literally just says that
![Screenshot_20240107_132830](https://github.com/NBZion/SteamModDownloader/assets/142307984/46412ab0-064b-4c0e-bfaa-98b191493206)

**Comment by NBZion** [comment]
are you sure its installed?

**Comment by NBZion** [comment]
did you do 
```
smd install
```

**Comment by NBZion** [comment]
And if so please show the logs to smd install if it fails

**Comment by Satyr-OS** [comment]
![Screenshot_20240108_012028](https://github.com/NBZion/SteamModDownloader/assets/142307984/23f4b90e-2b4a-44ce-924c-695b0ce3c596)

**Comment by Satyr-OS** [comment]
after looking around a bit i changed in smb script:
python3 -m env .clientEnv -> python3 -m venv .clientEnv
and it works.

**Comment by NBZion** [comment]
Oh I see, let me fix that in the next update

**Comment by NBZion** [comment]
issue resolved!
